### ISSUE TITLE
Unable to install latest version on Windows or OSX

### ISSUE THREAD

**Issue by dylanbutler** [viart/http-rewrite-middleware#2]
I would like to install this, but having trouble:

> npm install http-rewrite-middleware --save

npm WARN package.json phApp@0.1.106 No repository field.
npm http GET https://registry.npmjs.org/http-rewrite-middleware
npm http 200 https://registry.npmjs.org/http-rewrite-middleware
npm http GET https://registry.npmjs.org/http-rewrite-middleware/-/http-rewrite-middleware-0.1.4.tgz
npm http 200 https://registry.npmjs.org/http-rewrite-middleware/-/http-rewrite-middleware-0.1.4.tgz
npm ERR! Error: shasum check failed for C:\Users\DYLAN~1.BUT\AppData\Local\Temp\npm-9540\1392242451
49-0.7730466274078935\tmp.tgz
npm ERR! Expected: e2877d12ad9b929ea819923c65359e8cce9b6e11
npm ERR! Actual:   8e8c2646e3e933810d63420b770e5a4f37451784
npm ERR!     at C:\Program Files (x86)\NodeJS\node_modules\npm\node_modules\sha\index.js:32:8
npm ERR!     at ReadStream.<anonymous> (C:\Program Files (x86)\NodeJS\node_modules\npm\node_modules
sha\index.js:61:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:910:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

Should I report to @isaacs?

**Comment by viart** [comment]
Hi @dylanbutler, I guess this is a temporary NPM issue, I've just installed the package under OSX.

**Comment by viart** [comment]
Can you try to run `npm cache clean` and then retry `npm install http-rewrite-middleware --save`?
I believe this should help.

**Comment by dylanbutler** [comment]
After following your instructions, it worked! Must've been a temporary
issue.

On Wed, Feb 12, 2014 at 2:46 PM, Artem Vitiuk notifications@github.comwrote:

> Can you try to run npm cache clean and then retry npm install
> http-rewrite-middleware --save?
> I believe this should help.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/viart/http-rewrite-middleware/issues/2#issuecomment-34927904
> .

## 

Dylan Butler, Esq.
www.dylanbutler.com
(619) 414-8866
