### ISSUE TITLE
Port 8000 issue?

### ISSUE THREAD

**Issue by eduardoinnorway** [viart/http-rewrite-middleware#4]
Hi, I used grunt-connect-rewrite before with both "cg-angular" and "angular" generators, worked very good. Now I try to change to http-rewrite-middleware in a new project but the outcome is different what happens here is that:

$http.get('rest/user') will call localhost:9000/rest/user as expected and get a "NetworkError: 404 Not Found - http://localhost:9000/rest/user" error.

But it is actually available in localhost:8000/rest/user, that was not the case for "grunt-connect-rewrite", there it works calling port 9000 with no problems.

I cant make an app calling on "localhost:8000" then it will not work on prod and I will have to make to a task in Grunt to clean out all the "localhosts:8000" or something.

I have an issue also on Stackoverflow there you can see the code: http://stackoverflow.com/questions/29802171/http-rewrite-middleware-with-generator-cg-angular

**Comment by viart** [comment]
Hi @eduardoinnorway,

Not sure I fully understand you.

From your console's output it seems like you're adding rules to the one port (8000), but trying to use them on another (9000). i.e. You're opening `http://localhost:9000/` in the browser, so `$http.get('rest/user')` is doing request to `http://localhost:9000/rest/user`.

_and/or_

Which version of [grunt-contrib-connect](https://github.com/gruntjs/grunt-contrib-connect) do you use? I see they've changed the structure of a configuration per server... I'd try to move the `port` value from `connect.main.options.port` to `connect.development.options.port`.

**Comment by eduardoinnorway** [comment]
Hi Viart, thank you for taking your time to answer.

Version 0.6.0 of grunt-contrib-connect.

I should had been more clear, yes I see what it does on the conslole output, and that is what for me is strange is that everything worked before out of the box with "grunt-connect-rewrite" even with a late 2014 cg-angular app I did. Now wanting to move over to your awesome "http-rewrite-middleware
" I got stuck.

Try to set it up with cg-angular and you will see, https://github.com/cgross/generator-cg-angular

**Comment by eduardoinnorway** [comment]
This worked for me, solution for "cg-angular" generator:

connect: {
      main: {
        options: {
          port: 9000,
          hostname: 'localhost',
          base: '',
          middleware: function (connect, options) {
                  var middlewares = [];

```
              // RewriteRules support
              middlewares.push(rewriteModule.getMiddleware([
                  {from: '^/rest/user', to: '/json/user.json'}
              ]));

              if (!Array.isArray(options.base)) {
                  options.base = [options.base];
              }

              var directory = options.directory || options.base[options.base.length - 1];
              options.base.forEach(function (base) {
                  // Serve static files.
                  middlewares.push(connect.static(base));
              });

              // Make directory browse-able.
              middlewares.push(connect.directory(directory));

              return middlewares;
          }
    },
  }
}
```

**Comment by viart** [comment]
Unfortunately, I don't have a time for trying `cg-angular`.

Do you run both servers from a single `gruntfile`?
