### ISSUE TITLE
Error: ENOTDIR

### ISSUE THREAD

**Issue by eduardoinnorway** [viart/http-rewrite-middleware#5]
This might have been better as a Stackoverflow, but I think I would get a faster answer here.

This will not work
{from: '^/rest/users', to: '/json/users/user-list.json'},
{from: '^/rest/users/banned/123', to: '/json/users/banned/123.json'}

Because /rest/users/banned/123 will map to '/json/users/user-list.json/banned/123'

With or without $ it will produce the same outcome.

**Comment by viart** [comment]
Not sure I understand the issue/question, but can you try this?

```
{from: '^/rest/users/banned/123$', to: '/json/users/banned/123.json'},
{from: '^/rest/users$', to: '/json/users/user-list.json'}
```

**Comment by viart** [comment]
@eduardoinnorway is your issue solved?
